- README.md
Some small tweaks to the LeoFS installation instructions.
> Improve LeoFS installation instructions

- api/V1/responseUtil.js
- api/V1/signedUrl.js
- models/util/util.js
Some variables that I forgot to rename when changing the config file.
> Changed some variables names to work with the new config file.

- README.md
- Server.js
- api/V1/AudioRecording.js
- api/V1/AuthenticateDevice.js
- api/V1/AuthenticateUser.js
- api/V1/Device.js
- api/V1/Group.js
- api/V1/Tag.js
- api/V1/ThermalVideoRecording.js
- api/V1/User.js
- api/V1/apidoc.js
- api/V1/index.js
- api/V1/signedUrl.js
- api/V1/util.js
- apidoc-intro.md
- apidoc.json
- apidoc.sh
- header.md
This PR adds complete API documentation and updates the server to serve up the docs when a request for the API root arrives.
> Add API documentation

- api/V1/Recording.js
- models/Recording.js
Also fixed a bug with not accepting users JWTs when getting recordings.
> Added the ability to download 'Recording' files.

- api/V1/Recording.js
Sort recordings without a timestamp underneath those that do, and then sort by id after that.
> Improve sorting of recordings

- api/V1/Recording.js
- api/fileProcessing/index.js
- models/Recording.js
- package.json
Change thermal data to be processed to mp4, added a recording name generated from the date and MIME type, and made the file processing to be able to update the recordings fields (can set MIME type by using this).
> Change thermal file type to mp4

- api/V1/Recording.js
- api/V1/Tag.js
- models/Recording.js
This also removed the ability to tag older model types, but this wasn't used or going to be used.
> Added ability to tag 'Recording' models.

- api/V1/Recording.js
- migrations/20171101055215-change-tagging-format-migration.js
- models/Tag.js
Changed model 'Tags' format and made a few changed to the API to improve tagging on web interface.
> Change tagging format

- .eslintrc.yml
We will no doubt want to tweak this more
> Beginnings of an eslint configuration

- README.md
- Server.js
- api/V1/Recording.js
- api/V1/signedUrl.js
- config/config_TEMPLATE.js
- models/util/util.js
- small tweak to allow minio to work
- extract S3 connection logic to it's own function
- updated config "leofs" section to the more generic "s3"
- updated docs
> Support minio 

- .eslintrc.yml
- Server.js
- api/V1/Recording.js
- migrations/20171123040730-add-comment-for-recordings.js
- models/Recording.js
Finishing off Cameron's PR from here: https://github.com/TheCacophonyProject/cacophony-api/pull/36
Added DELETE, and PATCH for "recordings".
Added new "comment" column to "recordings". Will be able to write a comment for recordings on the view page.
> Adding delete and patch

- api/V1/Recording.js
- api/V1/Tag.js
- migrations/20180103040428-add-tags-automatic.js
- models/Recording.js
- models/Tag.js
Tags now have an `automatic` flag which indicates that the tag was generated by an automatic classifier.
Recordings can now be selected according to any of the following criteria:
- 'any'
- 'untagged'
- 'tagged'
- 'automatic-only'
- 'human-only'
- 'automatic+human'
Also fixed up many eslint issues.
> Add support for automatic tags

- api/V1/Device.js
- models/Device.js
- models/Recording.js
- models/User.js
Also made some fixes to issues reported by eslint.
>  Allow superusers to have access to all recordings and devices

- api/V1/Tag.js
- api/V1/tagsUtil.js
- api/fileProcessing/index.js
This is required to support automatic tagging.
* Extracted out guts of recording tag POST handler so that it can be used for the file processing API as well
* Exposed setting a recording tag via the fileProcessing API
* Fixed a ton of errors reported by eslint
> Tagging via fileProcessing API

- api/V1/Device.js
- models/Device.js
- models/DeviceUsers.js
- models/Group.js
- models/User.js
Added ability to add and delete users from devices.
Changed GET API for devices.
> Added DeviceUsers API.

- api/V1/Device.js
- api/middleware.js
- models/Device.js
- models/Group.js
- models/User.js
- package-lock.json
- package.json
Started to implement express-validator.
> using express validator with Device API

- README.md
- config/config_TEMPLATE.js
- package-lock.json
- package.json
Just some documentation.  
Cheers
Clare
> Update starting docs

- api/V1/AuthenticateDevice.js
- api/V1/AuthenticateUser.js
- api/V1/Group.js
- api/V1/Recording.js
- api/V1/Tag.js
- api/V1/User.js
- api/V1/signedUrl.js
- api/middleware.js
- models/Group.js
- models/User.js
Added express validator to more of the API. Also some small changes to code style.
> Adding more express validator

- api/V1/Recording.js
The docs were missed when the args were added.
> Document the tagMode and tags query args of the Recordings API

- package-lock.json
- package.json
https://nvd.nist.gov/vuln/detail/CVE-2017-18214
> Upgrade moment beyond 2.19.3 to deal with security vulnerability

- test/README.md
- test/apibase.py
- test/deviceapi.py
- test/helper.py
- test/test_02_device.py
- test/test_03_group.py
- test/test_04_tagging.py
- test/testdevice.py
- test/testrecording.py
- test/testuser.py
- test/userapi.py
Added a test that tests get by tag, and get by tag type.
> Search test

- README.md
- Server.js
- config.js
- config/.gitignore
- config/app_test_TEMPLATE.js
- config/keys/.gitignore
- test/README.md
Now that there's only one configuration file it doesn't need to take a directory.
> The --config argument now takes a file rather than a directory

- .gitignore
- api/V1/AudioRecording.js
- api/V1/Recording.js
- models/AudioRecording.js
- test/deviceapi.py
- test/test_04_tagging.py
- test/test_05_audio_device.py
- test/test_07_user_thermal.py
- test/testdevice.py
- test/testrecording.py
- test/testuser.py
- test/userapi.py
This adds tests to check the downloaded content and metadata for audio and recordings, as well as deletion of recordings.
A few API documentation issues have also been fixed.
> More tests

- api/V1/Schedule.js
- api/middleware.js
- migrations/20180427021359-create-schedule.js
- models/Device.js
- models/Schedule.js
- models/User.js
- test/deviceapi.py
- test/helper.py
- test/test_10_schedule.py
- test/testdevice.py
- test/testuser.py
- test/userapi.py
Finished the schedule api now.   I haven't added any checking for the format of the schedule though.   
I will now move onto the web interface.
> Schedule api

- api/V1/AudioRecording.js
- api/V1/tagsUtil.js
- models/AudioRecording.js
- models/util/util.js
The /audiorecordings/:id/tags API is not used by the web UI.
> Remove (unused) audio tagging API and infrastructure

- api/V1/Recording.js
- api/V1/util.js
- test/test_06_user_audio.py
- test/test_07_user_thermal.py
- test/testrecording.py
- test/testuser.py
- test/userapi.py
Add tests for updating metatdata via the Recordings and AudioRecordings APIs.
Fix bug with recordings updates (fixes #92).
> Recordings update tests & fix Recordings PATCH API

- api/V1/util.js
> handles promise rejection

- api/middleware.js
> Added device and username to logs in request.

- migrations/20180611050145-recordings-dawn-dusk-cols.js
- models/Recording.js
This is part of merging AudioRecording into Recordings.
> Add relativeToDawn & relativeToDusk cols to Recordings

- api/V1/util.js
Audio file will be processed and uploaded to the object storage before responding to user. Preventing a 200 response when the object storage is full.
> Server responds with 500 not 200 when object storage is full.

- package-lock.json
- package.json
* Update sshpk to address security issues 
* Remove dependency on tcp-port-used. We're not using it any more and it has a security issue.
> More security fixes

- api/V1/Recording.js
- api/V1/util.js
- migrations/20180627034101-add-rawmimetype.js
- models/Recording.js
- test/testdevice.py
- test/testuser.py
In order appropriately handle raw content, it's useful to know the
MIME type. Handling for both CPTV and MP3 files has been taken care of.
This is part of the work of for merge AudioRecordings and Recordings.
> Add rawMimeType column to Recordings

- api/V1/File.js
- api/V1/Recording.js
- api/V1/Schedule.js
- api/V1/util.js
- api/middleware.js
- test/apibase.py
- test/deviceapi.py
- test/test_07_user_thermal.py
- test/testdevice.py
- test/testrecording.py
- test/testuser.py
- test/userapi.py
This code will allow us to upload recordings to the api server on behalf of a device.   The collector needs to have registered as a user to the website  first.
> Collector device upload

- api/V1/AuthenticateUser.js
- api/V1/User.js
- api/middleware.js
- migrations/20180830022142-add-index-to-email-migration.js
- models/User.js
- test/apibase.py
- test/db-seed.sql
- test/helper.py
- test/test_01_user.py
- test/testconfig.py
- test/testuser.py
- test/userapi.py
When registering a user requires an email now.
A user can login using either an email or username.
> Added user email

- api/V1/AudioRecording.js
- api/V1/AuthenticateDevice.js
- api/V1/AuthenticateUser.js
- api/V1/Device.js
- api/V1/Event.js
- api/V1/File.js
- api/V1/Group.js
- api/V1/Recording.js
- api/V1/Schedule.js
- api/V1/Tag.js
- api/V1/User.js
- api/V1/index.js
- api/V1/recordingUtil.js
- api/V1/responseUtil.js
- api/V1/signedUrl.js
- api/V1/util.js
- api/customErrors.js
- api/middleware.js
Fixes #59 
Also adds license headers for all API files
> Api message cleanup

- models/Recording.js
The raw filename now uses the date of it's recording for it's name.
> Fixes raw filename when downloading.

- api/V1/AuthenticateUser.js
- api/middleware.js
- test/apibase.py
- test/helper.py
- test/test_01_user.py
- test/userapi.py
This is to help frontend apps let users login with a email or username without checking it first.
> Added 'nameOrEmail' field to authenticate user

- docker-entrypoint.sh
- models/Device.js
- models/DeviceUsers.js
- models/Event.js
- models/EventDetail.js
- models/File.js
- models/Group.js
- models/GroupUsers.js
- models/Recording.js
- models/Schedule.js
- models/Tag.js
- models/User.js
- models/index.js
- models/util/util.js
- models/util/validation.js
- package-lock.json
- package.json
> Sequelize to v4

- api/V1/Recording.js
- api/V1/apidoc.js
- api/V1/recordingUtil.js
- models/Recording.js
- test/test_12_recordings_filter.py
- test/testdevice.py
- test/testuser.py
- test/userapi.py
Recording location coordinates are filter to an accuracy of 100m by default.
> Added filter options for recordings query.

- api/fileProcessing/index.js
- models/Recording.js
- test/conftest.py
- test/fileprocessingapi.py
- test/helper.py
- test/requirements.txt
- test/smoketest.py
- test/test_14_file_processing.py
- test/testconfig.py
Included is test infrastructure to support testing the file processing API.
>  Merge additionalMetadata when updating through file processing API

- api/customErrors.js
- api/middleware.js
- models/User.js
Mainly just removing the name of the error in the error messages. The name was not useful to the user and was often just "_error"
> More user friendly error messages

- .travis.yml
- test/__init__.py
- test/apibase.py
- test/check-style
- test/deviceapi.py
- test/helper.py
- test/requirements.txt
- test/smoketest.py
- test/test_01_user.py
- test/test_02_thermal_device.py
- test/test_03_group.py
- test/test_04_tagging.py
- test/test_05_audio_device.py
- test/test_06_user_audio.py
- test/test_07_user_thermal.py
- test/test_08_event.py
- test/test_09_audio_bait.py
- test/test_10_schedule.py
- test/test_11_global_permissions.py
- test/test_12_recordings_filter.py
- test/test_13_device_users.py
- test/testconfig.py
- test/testdevice.py
- test/testexception.py
- test/testrecording.py
- test/testuser.py
- test/userapi.py
...using the Black tool (https://github.com/ambv/black). This uses sensible rules and follows the mostly widely accepted Python coding style.
Also added a script to check formatting and TravisCI now runs it to ensure future work uses a consistent style.
> Fix style of Python code which implements tests

- Dockerfile
Our server side infrastructure is being upgraded so that's what we should be testing with.
> Switch to Ubuntu 18.04 and PostgreSQL 10

- api/V1/Schedule.js
- api/V1/recordingUtil.js
- api/fileProcessing/index.js
- api/middleware.js
- models/Device.js
- models/Event.js
- models/File.js
- models/Group.js
- models/Recording.js
- models/Track.js
- models/User.js
- models/util/util.js
- package-lock.json
- package.json
- test/test_device_users.py
Upgraded to Sequelize v5, required changing some functions as mentioned here:
https://github.com/sequelize/sequelize/blob/master/docs/upgrade-to-v5.md
Also required changing Device model reference to Group from groupId to GroupId
> Sequelize v5

- test/recording.py
- test/testuser.py
Quick cleanup of things I noticed while doing other things
> Quick clean up of identifiers in tests

- .travis.yml
... not allowed to write to /usr/bin
> Put nfpm in different location

- _release/cacophony-api.service
- _release/nfpm.yaml
- _release/postinstall.sh
- include a bunch of missed source files (!)
- deploy the systemd service with the package
- move the config to /etc/cacophony/api.js
- post installation: stop server, migrate, start, status
> Various release fixes

- package-lock.json
- package.json
https://nvd.nist.gov/vuln/detail/CVE-2018-16492
> Update extend dep to address CVE-2018-16492

- test/helper.py
- test/test_user.py
Went a bit further and parsed the JSON in the error message, any thoughts on breaking it out into another test or just leave it out?
> Add a test for Issue #19 to show working as expected

- README.md
- run
I added my user to the docker user group so i don't need to prefix docker commands with sudo and password. Have left the default run using sudo.
> Modify run file to support without using sudo

- .travis.yml
- README.md
- api/V1/Recording.js
- api/V1/recordingUtil.js
- api/fileProcessing/index.js
- docker-entrypoint.sh
- models/Recording.js
- run
- test/conftest.py
- test/helper.py
- test/recording.py
- test/test_file_processing.py
- test/test_recordings_get_by_tags.py
- test/test_user.py
- test/testuser.py
> Added transaction to file processing get API

- api/V1/Recording.js
- test/test_recordings_filter.py
- test/userapi.py
also added test to check limit
> fixed recordings query returning incorrect count

- migrations/20190606235238-cleanup-tags.js
- models/Recording.js
- test/test_recordings_get_by_tags.py
'missed track',
'multiple animals',
'trapped in trap',
'cool'
> Handle extra tags

- api/V1/Tag.js
- api/V1/recordingUtil.js
- api/fileProcessing/index.js
- api/middleware.js
fix bug where adding tags failed due to no user from file api
> parse success as a boolean

- fix-object-keys.js
It's more useful to have the date in the object key match the date of the source entity.
> Use source entity date when setting new object keys

- _release/build.sh
- docker-entrypoint.sh
Cron doesn't like its config files to be writable by anyone but the owner.
> Set correct mode on cron config file

- migrations/20190724130852-add-index-to-group.js
- models/Group.js
Adds an index to groupname and make it unique
> Make groupname unique

- api/V1/Device.js
- api/middleware.js
- models/Device.js
- test/deviceapi.py
- test/test_device_rename.py
- test/testdevice.py
Devices can change there name and group
> Device rename endpoint

- migrations/20190808050641-add-device-rename-history.js
- models/Device.js
- models/DeviceHistory.js
Added a device history table so can keep track of name and group changes of a device. Could be expanded in the future for location...
> Added device history table

- migrations/20191002224957-rename-bad-tracks.js
changes existing tags to consistent names, also updated in browse https://github.com/TheCacophonyProject/cacophony-browse/pull/254
> added migration

- migrations/20191111002157-track-index.js
- models/Recording.js
- models/Tag.js
- test/test_recordings_get_by_tags.py
- test/test_tracks.py
- test/testuser.py
changed recording query to query Tags and/or TracksTags tables when relevant.
also changed tests to add trackstags for animals instead of recording tags
> added index to tracks and trackstags

- api/V1/Schedule.js
- test/test_schedule.py
> Fix schedule API sending back too much info

- api/customErrors.js
- api/middleware.js
Also refactored the mapping of error messages to be simpler/functional style.
This addresses the serverside fixes for all of #207
> Update parseJSON middleware to work for objects or strings

- api/V1/AuthenticateUser.js
- Increase from one minute to 5 minutes
> Increase defautl expire time for user tokens

- _release/build.sh
.ts files need to be compiled before release!
> Adjust package build process to account for TypeScript

- api/V1/recordingUtil.ts
- api/V1/util.ts
- migrations/20200109220031-false-positive.js
migrationg to rename false positive tracks tags to false-positive
> added migration to rename false positives

- models/Group.ts
Sorry, I didn't realise there was some other code that was removed that involved some more munging of the data returned by this api endpoint.  I've now reinstated it, and the data returned should now be in the shape that the front-end expects.
> Restore deleted maipulation of groups

- models/Group.ts
Hopefully this will resolve all the UI regressions in the admin area.
> Add back devicename to group info.

- remove-dups.ts
Don't remove recordings with a NULL "recordingDateTime" as these may be recent uploads that are awaiting processing. This fixes an issue where recordings were being lost following a bulk upload of many recordings.
Also: log the recording type when deleting a recording.
> remove-dups: ignore recordings with a NULL "recordingDateTime"

- migrations/20200221232549-add-index-to-event-datetime.js
Speed up reporting queries that generate CSV files.  They're still pretty slow queries (up to 30secs for querying over a longer time period) but now they should be roughly O(n) rather than O(n^2)
> Add database migration to add an index to event dateTime field.

- .travis.yml
- api/V1/Device.ts
- api/V1/recordingUtil.ts
- beautify.sh
- config/app_test_default.js
- docker-entrypoint.sh
- migrations/20200109220031-false-positive.js
- migrations/20200304235418-device-group-unique.js
- models/DetailSnapshot.ts
- models/Device.ts
- models/Recording.ts
- prune-objects.ts
- remove-dups.ts
- test/test_device_group_names.py
- test/test_user.py
- test/userapi.py
remove unique devicename index, and make index on name + group
also change username, email, groupname and devicename to be case insensitive
> make devicename+group unique

- config/app_TEMPLATE.js
- report-service-errors.ts
added settings to work with local smtp
> update reporting to work with localhost:

- api/V1/Visits.ts
- api/V1/recordingUtil.ts
- test/test_visits.py
Visits page wasn't merging future unidentified events properly.
Also wasn't ordering the events or recording tracks correctly.
> Fix visits

- api/V1/Visits.ts
- api/V1/recordingUtil.ts
- models/Recording.ts
Return groupid and deviceid for processing so we can see the orignating device in cacophony processing
> use master tag in visits calculation

- api/V1/Visits.ts
- models/Recording.ts
- test/track.py
this is the model that was used, visits page needs this to filter tags on.
> return TrackTag.data.name in recordings query

- emailUtil.ts
- report-service-errors.ts
Actually use the html body,
and put \r\n in text body instead of \n
> tidy up email template

- api/V1/Group.ts
- api/V1/recordingUtil.ts
- api/middleware.ts
- migrations/20210120160000-create-stations.js
- models/Group.ts
- models/Recording.ts
- models/Station.ts
- models/User.ts
- models/index.ts
recordingDateTime and location, will be usefull for dennis and morepork detection
> Add processing fields

- .travis.yml
Travis couldn't build the release, due to the changes that I made to travis.yml.   This should hopefully fix that.
> Fix to build release

- api/V1/Device.ts
- api/V1/Group.ts
- api/V1/User.ts
- api/middleware.ts
- models/Device.ts
- models/DeviceUsers.ts
- models/GroupUsers.ts
- test-cypress/cypress/commands/api/camera.d.ts
- test-cypress/cypress/commands/api/camera.ts
- test-cypress/cypress/commands/api/events.ts
- test-cypress/cypress/commands/api/user.d.ts
- test-cypress/cypress/commands/api/user.ts
- test-cypress/cypress/commands/server.ts
- test-cypress/cypress/integration/alerts/device_stopped.ts
- test-cypress/cypress/integration/devices/device_authorization.ts
- test-cypress/cypress/integration/devices/device_names.ts
- test/test_device_users.py
Added a new api command to get a single device by device and groupname. 
Added tests to test it.
> Fix device

- api/V1/Device.ts
- api/V1/Visits.ts
- api/V1/recordingUtil.ts
- api/middleware.ts
- models/Device.ts
- models/DeviceUsers.ts
- models/GroupUsers.ts
- models/Recording.ts
- test-cypress/cypress/commands/api/camera.d.ts
- test-cypress/cypress/commands/api/camera.ts
- test-cypress/cypress/commands/api/events.ts
- test-cypress/cypress/commands/api/user.d.ts
- test-cypress/cypress/commands/api/user.ts
- test-cypress/cypress/integration/devices/device_authorization.ts
Calculate audiobait events seperately to visits, then combine. This speeds up the request
Also set location before setting station id
> Visits speed

- api/V1/Visits.ts
- models/Recording.ts
- models/Track.ts
- models/TrackTag.ts
- test/helper.py
- test/test_alerts.py
- test/testuser.py
- test/track.py
Only send alerts on master tag
> Alert master

- api/V1/Device.ts
- test-cypress/cypress/commands/api/camera.d.ts
- test-cypress/cypress/commands/api/camera.ts
- test-cypress/cypress/integration/devices/device_names.ts
- Added option for a device to set it's salt ID.
> Added option to set salt ID when creating a device
