Server.js

This is so the web interface running on a different port/domain can access the API.
This could cause security issues with Cookies but JWTs are used instead of Cookies.
Links about CROS, and JWT.
https://developer.mozilla.org/en-US/docs/Web/HTTP/Access_control_CORS
https://auth0.com/blog/angularjs-authentication-with-cookies-vs-token/

Adding headers to allow cross-origin HTTP request.

---

README.md
package.json

Cleaned up wording or added extra details to (hopefully) make installation a little easier.
Also moved node-gyp into package.json instead of asking the user to install it separately.

Clarify install instructions

---

api/V1/Recording.js

The recordings/get/:id API was unintentionally modifying the global model.Recording.userGetAttributes list. This was causing rawFileKey to be added to unrelated queries. After enough calls to this API the list of requested columns became so large the query column limit was reached causing the DB to reject them.

Don't add rawFileKey to models.Recording.userGetAttributes

---

.eslintrc.yml
api/V1/Device.js
api/V1/Recording.js
migrations/20171122123700-add-deviceusers.js
models/Device.js
models/DeviceUsers.js
models/Recording.js
models/User.js

In some cases it's useful to be able to give a user access to a device's recordings when using group membership is cumbersome. This change introduces a new DeviceUsers table which allows users to access devices. The pre-existing (unused)  user(1) : device(M) association has been removed.
This change also moves all the recording query logic into the model where it should be. This makes it easier to share query functionality between the query and "just get one" aspects.
Still to do:

Allow users to have direct access to devices

---

api/V1/Group.js
api/V1/Recording.js
api/V1/User.js
migrations/20171201023936-add-superuser.js
models/Group.js
models/GroupUsers.js
models/Recording.js
models/User.js

closes #39 
API added/changed to help with group admin on web:
- GET /api/v1/groups 
- POST /api/v1/groups/users
- DELETE /api/v1/group/users
- GET /api/v1/users This was changed to take a sequelize 'where' statement so you can get users ID, as users IDs are used when adding, removing users from groups.
Added 'superuser' to users. Adds ability to add/remove users from any group.

User & group management APIs

---

api/V1/tagsUtil.js

This happens when tagging is done via the fileProcessing API.

request.user is undefined when there's no authenticated user

---

api/V1/Recording.js
models/Recording.js

A tag mode of "no-human" returns recordings which are untagged by humans - either not tagged at all or only just automatically tagged.
The recordings query endpoint now accepts a "tags" field which takes an array of tags to match. These are ORed together. A virtual tag type of "interesting" will match tags which are *not* false positive or bird.

Add "no-human" tag mode and supporting querying for specific tags

---

migrations/20180207020240-recording_indexes.js

These greatly speed up most recordings queries we do, but especially help with the next/prev "interesting" queries.

Added more indexes on Recordings table

---

api/V1/AudioRecording.js

The update to middleware based authentication wasn't applied to the AudioRecordings API which meant that authentication for this part of the API was broken.

Fix AudioRecordings authentication

---

api/V1/AudioRecording.js
api/V1/Recording.js
api/V1/User.js
api/V1/util.js
api/middleware.js
models/Group.js

This PR fixes authentication for audio uploads which was broken by the recent change to use field verification middleware. It also fixes numerous other issues I ran into while troubleshooting.
The root issue was that the `isFromADevice` no longer works with the new middleware in place. It will go away soon anyway.
Other highlights:
* group addition was broken because the User API was requiring a `where` argument
* device and user names now need to be only 3 chars long - 8 was a bit draconian
* various typos fixed

Fix audio uploads & various other issues

---

api/V1/AuthenticateDevice.js
api/V1/AuthenticateUser.js
api/V1/Device.js
api/V1/Group.js
api/V1/User.js
api/middleware.js

Replace the API which returns all the users matching some criteria with one which returns the details for just one username. The latter is the all the web UI actually wants.
It's also good to avoid APIs which take raw sequelize strings as are security risks as and limit our implementation flexibility.
The web UI is being updated to switch to this new API.

/api/V1/users -> /api/V1/users/:username

---

config.js
config/app_TEMPLATE.js
logFiles/.gitignore
logging.js
models/index.js

Let systemd manage the log output instead of having cacophony-api manage its own log files. This also avoids the confusion of having different log levels spread across different files.
Sequelize's logs are now also sent through winston (at debug). This allows them to be turned off by selecting a log level of info or higher.
A default log level is now set so that database migrations work again.
Closes #53.

Log to console only

---

test/conftest.py
test/helper.py
test/test_01_user.py
test/test_02_thermal_device.py
test/test_03_group.py
test/test_04_tagging.py
test/test_05_audio_device.py

This makes it easier to make the Helper class available to tests. Using the "module" scope means that the helper is only instantiated once per test module.
Relevant docs: https://docs.pytest.org/en/latest/fixture.html

Introduce "helper" fixture

---

api/V1/requestUtil.js
api/V1/responseUtil.js
api/V1/util.js
models/util/util.js
test/__init__.py
test/conftest.py
test/deviceapi.py
test/helper.py
test/test_05_audio_device.py
test/test_06_user_audio.py
test/testconfig.py
test/testdevice.py
test/testrecording.py
test/testuser.py
test/userapi.py

This implements tests for the following URLs:
* DELETE api/V1/audiorecordings/:id
* GET api/V1/audiorecordings/:id (and then actually validating downloads)
* GET api/V1/audiorecordings/
Additionally:
* The missing `responseUtil.invalidDataId` function was added
* GET api/V1/audiorecordings/:id was changed to return a 400 if file processing hadn't completed yet
* Processing is skipped based on the filename as well as the mime type 
* Various typos in the JavaScript code were fixed
* pytest will now produce detailed assertion reports in our test helper modules.

More audio recording tests

---

models/util/util.js

Will now ignore the mime/type from the uploaded file and get it from the file name extension.
Tested locally uploading .3gp and .m4a from computer and a .m4a from a phone.

Gets mime-type from file extension

---

api/customErrors.js

When parameter validation fails, instead of logging a traceback with
no useful information, log the validation issues instead.
To support this, CustomErrors are now implement toString() as well as
toJson().

Log validation error details

---

api/V1/util.js

When getFileData fails reponseUtil.invalidFileRequest is called and
then an error is thrown. The thrown error is then picked up by the
catch handled which then ends up calling
responseUtil.invalidDatapointGet, resulting in 2 HTTP responses being
sent (not valid).
This is a likely fix for one of the issues reported in #71.
This code is all going away soon but it's good to fix this in the meantime.

Avoid double response when audio recording not found

---

models/util/util.js
package-lock.json
package.json
prune-objects.js

Changes here:
* package-lock.json changes due to npm upgrade 
* Add dependency on `commander`
* Upgrade `pg` to 5.1.0 to get the promise based query API. There are later versions but our
version of `sequelize` doesn't support them.
* Add prune-objects.js. This new command line tool will remove objects from the S3 (Minio)
server that are no longer referenced by the database.

New utility to remove unreferenced objects from the object store

---

.gitignore
Dockerfile
docker-entrypoint.sh
docker-start.sh

* Configure PostgreSQL in docker image instead of in the docker entry
point. There no reason to delay this until container startup.
* Simplify stopping of the container
* Expose PostgreSQL server port from container. This is useful for
development and confirming DB contents from the
outside. PostgreSQL's port is exposed at 5400 to avoid collisions
with a PostgreSQL server on the host.
* Avoid the need for the container pid file Given that a static container name is used, the pid file is unnecessary.
* Move minio startup to docker-entrypoint. This makes more sense given
that setting up Minio doesn't depend on the cacophony-api
code. This also speeds things up somewhat.

Docker improvements

---

models/Recording.js

This helps cacophony-processing to know what to do with a recording.

Return mime types from fileProcessing API

---

api/V1/AudioRecording.js
api/V1/File.js
api/V1/Recording.js
api/V1/Schedule.js
api/V1/index.js
api/V1/recordingUtil.js
api/V1/signedUrl.js
api/V1/util.js
migrations/20180802021921-move-audio-to-recordings.js
models/AudioRecording.js
models/Recording.js
test/test_05_audio_device.py
test/test_06_user_audio.py
test/test_07_user_thermal.py
test/testuser.py
test/userapi.py

The pre-existing AudioRecordings API still exists but it now interacts with the Recordings table instead. The AudioRecordings API is now marked as deprecated. Most of the API handler logic for dealing with recordings has been moved out to api/V1/recordingUtil.js so that it can be shared by the Recordings and AudioRecordings APIs.
A DB migration is included which imports all audio recordings into Recordings.

Store audio recordings in the Recordings table

---

api/V1/AudioRecording.js

The UI doesn't always pass these (i.e. when retrieving details for a single recording).

AudioRecordings: make offset & limit optional

---

api/V1/AudioRecording.js
test/test_06_user_audio.py
test/testuser.py
test/userapi.py

recordingUtil.query() only looks in query params which meant the limit, offset and where fields were being ignored.
Also fixed how `where` params are sent to the API server by the tests. The tests where using an undocumented way of doing this which didn't match what the UI uses.

Copy AudioRecordings query params from headers to query params

---

api/V1/AudioRecording.js
api/V1/AuthenticateDevice.js
api/V1/AuthenticateUser.js
api/V1/Device.js
api/V1/Event.js
api/V1/File.js
api/V1/Group.js
api/V1/Recording.js
api/V1/Schedule.js
api/V1/Tag.js
api/V1/User.js
api/fileProcessing/index.js
api/middleware.js

This removes the uses of the general `check` function and uses more specific express-validator functions like `param` `header` `body` `query`
https://express-validator.github.io/docs/check-api.html

Tidy up middleware checks.

---

package.json

This allows us to run database migrations with `npm run db-migrate`.

Add db-migrate scripts target

---

api/V1/Device.js
models/Device.js
test/test_13_device_users.py
test/testuser.py
test/userapi.py

`GET /api/V1/devices/users`
This can be called by any user who has admin privs for the device.
Also removed duplicated Device.userPermissions method.

 Add API to return details of users who can access a device 

---

.travis.yml
api/V1/AudioRecording.js
api/V1/Event.js
api/V1/Recording.js
api/V1/apidoc.js
api/V1/recordingUtil.js
api/middleware.js
models/Event.js
models/Recording.js
package-lock.json
package.json
test/conftest.py
test/deviceapi.py
test/test_08_event.py
test/testdevice.py
test/testuser.py
test/userapi.py

* Tighten up handling of get events query params
- Automatic int conversion
- Fixed bug when setting default for `limit`
- Cleaner default handling
* Upgrade express-validator to address various sanitisation bugs
* Rationalise query test helpers
* Replace Events query "where" param with separate query params. This is safer and helps to avoid lock-in to sequelizejs.

Tidy up Events api

---

api/V1/recordingUtil.js
models/Recording.js

`Recording.getOne` is now `Recording.get` and now takes the required
permission to access the recording. This cleans up a bunch of call
sites, ensures that a permissions check is always done and simplifies
implementation of track based tagging (in progress).

Refactoring of recording retrieval

---

test/test_03_group.py
test/test_07_user_thermal.py
test/test_09_audio_bait.py
test/test_10_schedule.py
test/test_11_global_permissions.py
test/test_13_device_users.py

The `messages` argument to pytest.raises is now deprecated and
generates distracting warnings when pytest is run. There is no
replacement for that feature of pytest.raises.

Fix warnings related to pytest.raises

---

models/Recording.js
models/User.js
test/test_device_users.py
test/testuser.py

Users with access through DeviceUsers could query recordings but not download them. This is a recently introduced regression.
Also added tests to cover this situation.

Allow users with direct access to device to see recordings again

---

.gitignore
.travis.yml
README.md
_release/build.sh
_release/nfpm.yaml
_release/postinstall.sh

TravisCI will now build Debian release packages for tagged revisions and upload them to Github Releases.

Build releases in TravisCI

---

_release/build.sh
_release/cacophony-api.service
_release/nfpm.yaml
_release/postinstall.sh

For various reasons npm doesn't like you packaging up dependencies on
one host and copying them elsewhere. The .deb now installs and
rebuilds dependencies on the server.
Also:
- Fixed path to node binary
- have the .deb depend on libpq-dev so that the pq client library can
be built
- Move the previous config file to new location and symlink to
it (needed for DB migrations to work)
- Unused npm dependeices are pruned on every upgrade
- API docs are now re-built on the server instead of being included in
the package.

Deployment fixes

---

api/middleware.js

In lines 266 to 268 middleware.js has
if (!("user" in request)) { throw new customErrors("No user specified.", 422); }
The call should be to the function ClientError in the module customErrors
if (!("user" in request)) { throw new customErrors.ClientError("No user specified.", 422); }

Fixed call from middleware.js to customErrors.js

---

api/V1/responseUtil.js

(200 <= 400<= 299) evaluates to true in JS land, as it just does the first bit then returns true (unlike Python).
Due to this our success boolean is true 100% of the time! I know the plan is to phase out the success flag, but might as well fix it anyway (hopefully nothing downstream depends on this bug 😁)
Copy paste the below in to you browser console for a demo:
```
statusCode=400;
console.log(200 <= statusCode <= 299);
console.log(200 <= statusCode && statusCode <= 299);
statusCode=200;
console.log(200 <= statusCode <= 299);
console.log(200 <= statusCode && statusCode <= 299);
```

Fix a bug where the success boolean always returns true due to JS not doing multi comparisons

---

api/V1/User.js
api/customErrors.js
api/middleware.js
models/User.js
test/apibase.py
test/helper.py
test/test_middleware.py
test/test_user.py
test/testexception.py
test/testuser.py
test/userapi.py

Added support for PATCHing /api/v1/users with fields directly in the body as described in #199.
Also fix #205, all fields are now properly validated.
Reworked the way Error constructors are handled to make use of new language features. This way is better in terms of output and is also more concise.
Removed catch block in middleware that didn't need to be there that I added in an earlier PR, can instead be caught in the global error handler.
Reworked the User hooks to handle password hashing as they were being double hashed with the rework of the validation.
Fixed response code for invalid JSON to return a 422 rather than a 500.
Added tests for user PATCH and POST to prevent regression. Added middleware tests to check some status codes are as expected.

Initial work for #199, support both legacy and new version of the PATCH endpoint.

---

models/Recording.js
test/testdevice.py
test/testuser.py

A number of important fields where removed from the recordings search
API recently. This broke audio_download.py. These have been mostly
brought back and tests have been added for the search result fields.

Add various fields back to query results

---

DATA-MODEL.md
api/V1/Tag.js
api/V1/recordingUtil.js
migrations/20190605011805-tag-cleanup.js
models/Recording.js
models/Tag.js
test/recording.py
test/test_global_permissions.py
test/test_recordings_get_by_tags.py
test/test_tagging.py
test/userapi.py

- Unused tag fields have been removed:
- `number`
- `trapType`
- `sex`
- `age`
- New `version` field added
- `animal` renamed to `what`
- `event` renamed to `detail`
- `animal` and `event` are supported for tag creation and reported as aliases when retrieving recordings and querying

Tag API clean up

---

_release/cacophony-api-prune-objects
_release/nfpm.yaml
api/V1/File.js
api/V1/recordingUtil.js
api/V1/util.js
prune-objects.js

* Use a type prefix for the object keys: This allows prune-objects to more safely remove unused keys by only operating on these prefixes. These prefixes could also help make management of the object store easier.
* prune-objects now only acts on specific object key prefixes 
* Run prune-objects daily via cron

Make object pruning safer and run pruning daily

---

fix-object-keys.js

This is required for safer pruning (see prune-objects.js).

New script for one-off addition of prefixes to object keys

---

_release/cacophony-api-prune-objects

This adds timestamps and is preferable to receiving a daily email.

Send prune-objects output to syslog

---

Dockerfile
docker-entrypoint.sh
run

- Add --no-cache arg to run helper script. This forces all Docker images to be rebuilt - useful for debugging TravisCI failures.
- Use a fixed version of mc. Upstream have been making breaking changes to the command line args lately so stick with a specific version.
- Just use curl for all Dockerfile downloads instead of a fix of wget and curl.
- Remove --no-autocompletion arg to mc. It no longer supports this.

Add run --no-cache option and fix mc again

---

api/V1/File.js
api/V1/Recording.js
api/V1/Reprocess.js
api/V1/apidoc.js
api/V1/recordingUtil.js
config/app_TEMPLATE.js
config/app_test_default.js
models/DetailSnapshot.js
models/File.js
models/Recording.js
package-lock.json
package.json
test/deviceapi.py
test/fileprocessingapi.py
test/recording.py
test/test_file_processing.py
test/test_report.py
test/test_tracks.py
test/testuser.py
test/track.py
test/userapi.py

This new endpoint which takes the same query parameters as the main query API but generates a CSV. This CSV includes extra information such as details of the most recently played audio bait event.
To faciltate this change the recording query logic has been factored out into its own query builder object. The creation of the tests for this feature lead to various improvements in the API server test infrastructure.

New recordings CSV export API endpoint 

---

models/Recording.js

This might have been causing occasional test failures.

Fix dubious filter expression for CSV report audio bait events

---

.travis.yml
test/check-style
test/pyproject.toml

This avoids custom tooling and hopefully helps with IDE support (pyproject.toml is becoming a defacto standard)

Replace check-style script with pyproject.toml

---

api/V1/AuthenticateDevice.js
api/V1/AuthenticateUser.js
api/V1/Device.js
api/V1/Recording.js
api/V1/User.js
api/V1/signedUrl.js
api/auth.js
test/test_report.py
test/testuser.py
test/userapi.py

- added /token endpoint which generates a short-lived JWT for a user
- these tokens are now accepted by the report endpoint
- lots of refactoring and cleanup of authentication code 
Still to come:
- further auth refactoring (it can be simplier and "simple is Good" when it comes to authentication
- limit temporary tokens to specific parts of the API

Allow CSV reports to be generated using a JWT argument

---

api/V1/Recording.js
test/helper.py
test/test_device_query.py
test/test_user_thermal.py
test/testuser.py
test/userapi.py

This is still be used by Sidekick in the wild so we need to support it for a little longer.
Also fixed sporadically failing device query tests.

Restore the legacy /api/v1/recordings/:devicename POST endpoint 

---

_release/cacophony-api-remove-dups
_release/nfpm.yaml
remove-dups.js

Duplicate recordings are identified by (DeviceId, recordingDateTime).
The recording with the lowest id will be kept. Recordings with an
updatedAt timestamp within the last 30 mins are ignored.

Introduce a cron job to remove duplicate recordings

---

_release/build.sh

This file was being deployed as writeable meaning that cron wasn't
running it.

Ensure that cacophony-api-remove-dups isn't group writeable

---

Server.js

This will allow Cacophony Browse to use JSON objects instead of url encoding.
The added headers are standard ones that are basically always enabled as seen below and on numerous other guides about CORS
https://enable-cors.org/server_expressjs.html
The one we really care about is Content-Type so we can send JSON.
#199 and #207 rely on this fix to get Cacophony Browse in spec as it currently used form encoding which is messier and less flexible.

Add additional CORS Access-Control-Allow-Headers that are standard

---

api/V1/Recording.js

The query can take a long time and exceed Express' default 2min
timeout. We will improve the query but this will do in the mean time.

Set longer request timeout for report endpoint

---

api/V1/User.js

Fixes #199, Fixes #207 
The final work to remove the string JSON fields. The PATCH users endpoint is only used by Cacophony Browse and it's now using the real JSON, so we can now remove this converter.
The rest of the endpoints support both ways, and that's probably the best way to leave them, as then we don't have to double check everything's migrated, but any new consumers, as well as Cacophony Browse, can do it the cleaner way.

Remove now unused conversion from data field to body

---

api/V1/Recording.js
api/V1/apidoc.js

- Changed from `dateTime` to `recordingDateTime`
- Separated out Order from `BaseQueryParams` as `BaseQueryParams` is used in the `Files` API documentation where the order example is not relevant.

Fix Recording GET order example

---

api/V1/File.js
api/V1/recordingUtil.js
api/V1/util.js
models/Recording.js
test/recording.py
test/test_audio_device.py
test/test_file_processing.py
test/test_recordings.py
test/testuser.py
test/userapi.py

Fixes #38, Fixes #130
#38 
Update Recording delete to also delete the S3 files in the background.
Will log a warning if it wasn't deleted but will still return 200 before that results and no matter the status of the S3 deletions.
Didn't add a test for this but you can verify with minio/mc, create recording, GET it and note the rawFileKey, configure mc if you haven't already: `mc config host add s3 http://localhost:9001 minio miniostorage `, then query the file such as `mc ls s3/cacophony/raw/2019/12/19/c4b2b587-a463-45e6-a499-40b95bd25c1b`, should return the file and size. Delete the file through UI. Run the mc ls command again and the it should say file not found.
#130 
Update recording JWTs to only apply if the file exists
Extracted out a method to get the filesize of files in S3 to …

Fix 38 & 130, delete recording files from S3 when recording is deleted, and dont return JWTs if files don't exist

---

_release/build.sh

Too many files were being left out of the build. Go back to the `git archive` approach and just remove the `.ts` files once the release is ready.

Further build fixes

---

models/Group.ts

I stopped group users from being bundled with getting groups, but it turns out some front-end views were relying on that.  Put it back for now and explore better solutions in the future?

Restore GroupUsers to unbreak groups admin view

---

_release/postinstall.sh

Without this the postinstall script can pause waiting for the pager to end. This is confusing to the user.

Avoid systemctl pager usage in postinstall script

---

api/V1/Schedule.ts
models/DetailSnapshot.ts

- Make the `devices` field always set when getting schedule. Fixes a error in cacophony-browse-old where you couldn't add a schedule to a device that didn't already have a schedule set.
- Specify sequelise to use equals when comparing the details JSONB for a event. 
When not set this is an example of the SQL generated 
`AND (CAST(("DetailSnapshot"."details"#>>\'{foo}\') AS DOUBLE PRECISION) = ARRAY[1,2,3] AND CAST(("DetailSnapshot"."details"#>>\'{test2}\') AS DOUBLE PRECISION) = 2)`
Resulting in `SequelizeDatabaseError: operator does not exist: double precision = integer[]`

Add system err event

---

prune-objects.ts

When recordings are uploaded they are added to the object store then when finished uploading they are added to the database. This delay is to prevent recordings getting deleted as they are in the processing of uploading.

Added delay between getting keys from object store and DB

---

api/middleware.ts

This fixes the incorrect assumption that parsing a json string successfully always returns an object.
In reality it can be an object or literal which is stringified multiple times, and JSON.parse() will only unwrap one layer of this at a time.

Fix parseJSON middleware handling of json strings

---

api/V1/Event.ts
api/V1/Schedule.ts
api/V1/apidoc.js
api/V1/eventUtil.ts
api/V1/index.ts
test/test_event.py
test/testuser.py
test/userapi.py

Users can add events on behalf of devices same way that they can add recordings for devices.

Add user event upload

---

api/V1/Event.ts
api/V1/eventUtil.ts
test/test_event.py

The event api allowed event types with '-' in them and many events types have these spaces in them.  However the get events request didn't allow anything other than alpha characters.   This anomaly how now been fixed.

Fixed inconsistency in the event-type name checking.

---

api/V1/recordingUtil.ts
emailUtil.ts
models/Recording.ts
models/TrackTag.ts

Previous change to remove EventDetail as a requirement from sequelize join (to speed up query) broke the if statement as previously checking just for event was enough to ensure eventdetail also existed.

check for null value, also add trackid to alert link
